#!/bin/sh

FILE=$1
W=$2
H=$3
X=$4
Y=$5

# Create cache folder if it doesn't exist
THUMBNAILS="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnails"
[ -d "$THUMBNAILS" ] || mkdir -p "$THUMBNAILS"

case "$(file -Lb --mime-type "$FILE")" in
    image/*) kitty +icat --silent --transfer-mode file --place "${W}x${H}@${X}x${Y}" "$FILE" ;;
    audio/*) mediainfo "$FILE" ;;
    video/*)
        CACHE="$THUMBNAILS/$(realpath "$FILE" | md5sum - | cut -d ' ' -f1)"
        [ -f "$CACHE" ] || ffmpegthumbnailer -i "$FILE" -o "$CACHE" -s 0
        kitty +icat --silent --transfer-mode file --place "${W}x${H}@${X}x${Y}" "$CACHE"
        ;;
    */pdf)
        CACHE="$THUMBNAILS/$(realpath "$FILE" | md5sum - | cut -d ' ' -f1)"
        [ -f "$CACHE.jpg" ] || pdftoppm -jpeg -f 1 -singlefile "$FILE" "$CACHE"
        kitty +icat --silent --transfer-mode file --place "${W}x${H}@${X}x${Y}" "$CACHE.jpg"
        ;;
    application/zip) atool --list -- "$FILE" ;;
    application/gzip) bsdtar --list --file "$FILE" ;;
    text/*) bat -f "$FILE" ;;
esac

exit 1
