#!/bin/sh

xset r rate 300 50

setxkbmap -option caps:swapescape

xwallpaper --zoom ~/Pictures/bg.jpg

picom --experimental-backends &

for program in dwmblocks unclutter dunst; do
    pidof -s "$program" || "$program" &
done

exec dwm
