#!/bin/sh

xset r rate 300 50

setxkbmap -option caps:swapescape

xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

xwallpaper --zoom "${XDG_DATA_HOME:-$HOME/.local/share}/bg.png"

pidof -s picom || picom --daemon --config /dev/null --backend glx --glx-no-stencil --glx-no-rebind-pixmap --vsync
pidof -s easyeffects || easyeffects --gapplication-service &

for program in pipewire unclutter dunst dwmblocks; do
    pidof -s "$program" || "$program" &
done

exec dwm
